"""first-sample

Revision ID: 7fb4daea507f
Revises:
Create Date: 2025-10-20 22:36:05.281349+09:00

# ------------------------------------------------
# DB Schema Migration
# ------------------------------------------------

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fb4daea507f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("id", name=op.f("uq_users_id")),
    )

    # サンプルデータ挿入
    op.bulk_insert(
        sa.table("users", sa.column("id", sa.Integer), sa.column("name", sa.String)),
        [
            {"id": 1, "name": "sampleUser1"},
            {"id": 2, "name": "sampleUser2"},
            {"id": 3, "name": "sampleUser3"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
